### PR TITLE
Add cookie persistence (`spc_show`)

### PR DESCRIPTION
**Pull request by MSWS**
Adds cookie persistence when clients toggle viewing clip brushes on/off.
Cookie is `spc_show` and is Protected.

### CODE REVIEW

**Comment by GAMMACASE** [comment]
I'm not really positive with this change since it might get annoying rather then helpful. There are maps where this plugin doesn't really perform well and playing with it toggled on might be not an option, thus you end up toggling the plugin anyway. And since this plugin is mainly an utility to see the clips around you on a specific map, I'm not sure why it should be persisted between map changes.

Maybe a cvar to enable this functionality would do it, not sure.

**Comment by GAMMACASE** [comment]
Also please, make sure you have the same variable naming style (ghShowCookie -> gShowCookie and etc.) and that the plugin is actually compiles, cuz I see gBShow[client] usage, but it's not defined anywhere.

**Comment by MSWS** [comment]
> Also please, make sure you have the same variable naming style (ghShowCookie -> gShowCookie and etc.) and that the plugin is actually compiles, cuz I see gBShow[client] usage, but it's not defined anywhere.

Should be fixed, thanks for pointing it out.

**Comment by GAMMACASE** [comment]
> I'm not really positive with this change since it might get annoying rather then helpful. There are maps where this plugin doesn't really perform well and playing with it toggled on might be not an option, thus you end up toggling the plugin anyway. And since this plugin is mainly an utility to see the clips around you on a specific map, I'm not sure why it should be persisted between map changes.
> 
> Maybe a cvar to enable this functionality would do it, not sure.

So what are your thoughts on this?

**Comment by MSWS** [comment]
> > I'm not really positive with this change since it might get annoying rather then helpful. There are maps where this plugin doesn't really perform well and playing with it toggled on might be not an option, thus you end up toggling the plugin anyway. And since this plugin is mainly an utility to see the clips around you on a specific map, I'm not sure why it should be persisted between map changes.
> 
> > 
> 
> > Maybe a cvar to enable this functionality would do it, not sure.
> 
> 
> 
> So what are your thoughts on this? 

It would be funny to have a cookie to toggle another cookie...

**Comment by GAMMACASE** [comment]
I'm not suggesting a cookie to toggle another cookie, but rather a server side convar to enable persistence in this plugin for these server owners that do want that functionality enabled, since I'm definitely would be the one who would turn that off due to reasons stated above.

**Comment by MSWS** [comment]
> I'm not suggesting a cookie to toggle another cookie, but rather a server side convar to enable persistence in this plugin for these server owners that do want that functionality enabled, since I'm definitely would be the one who would turn that off due to reasons stated above.

Sure, but ideally it would be per client whether they want persistency or not. Hence two cookies.

**Comment by GAMMACASE** [comment]
Sure that is also an option, but it's quite an overcomplication for such a change imo. Either way there should be something to toggle this feature down either on a global server scale or on a personal preference.

**Comment by GAMMACASE** [comment]
Alright now looks good to me, thanks for the pr!

**Pull request merged**
